name: Mule CICD with Mule Maven1

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven And push to exchange
      env:
        anypointUsername: ${{ secrets.ANYPOINT_USERNAME }}
        anypointPassword: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        mvn deploy -s ./.maven/settings.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production-blue
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Deploy to CloudHub
      run: |
         mvn deploy -DmuleDeploy -s ./.maven/settings.xml
        
